from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
import pandas as pd
import yaml


PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.diagnose_beam_search_validation import (
    build_vocab_from_files,
    get_environment_snapshot,
    list_site_paths,
    reconstruct_site_meta,
    split_holdout_paths,
)
from src.io_f import read_data_file


SUMMARY_KS = (1, 5, 10, 20, 50)
SUMMARY_THRESHOLDS_M = (3, 5)
MISSING_WIFI_RSSI = -999.0
PREDICTION_ARTIFACT_COLUMNS = {
    "site_id",
    "path_id",
    "floor",
    "timestamp",
    "point_index",
    "x",
    "y",
    "pred_x",
    "pred_y",
    "model_kind",
    "feature_source",
}
ARTIFACT_GENERATION_COMMAND = (
    "python scripts/diagnose_beam_search_validation.py "
    "--absolute-point-artifact-only "
    "--site-summary-source data_processing/processed/absolute_holdout_summary.json "
    "--point-pred-out data_processing/processed/absolute_holdout_point_predictions.csv"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Batch diagnose candidate recall failure modes for absolute holdout paths.")
    parser.add_argument("--config", default="configs/kaggle_train_config.yml")
    parser.add_argument(
        "--prediction-artifact",
        default="data_processing/processed/absolute_holdout_point_predictions.csv",
        help="Point-level pure absolute holdout predictions generated by diagnose_beam_search_validation.py.",
    )
    parser.add_argument(
        "--site-summary-source",
        default="data_processing/processed/absolute_holdout_summary.json",
        help="JSON file used to recover the site list and base holdout settings.",
    )
    parser.add_argument("--site-list", default="", help="Optional comma-separated override for site ids.")
    parser.add_argument("--holdout-fraction", type=float, default=None)
    parser.add_argument("--max-holdout-paths", type=int, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--connect-radius", type=float, default=5.0)
    parser.add_argument("--catastrophic-threshold-m", type=float, default=20.0)
    parser.add_argument(
        "--path-out",
        default="data_processing/processed/hard_site_candidate_recall_paths.csv",
    )
    parser.add_argument(
        "--site-out",
        default="data_processing/processed/hard_site_candidate_recall_sites.csv",
    )
    parser.add_argument(
        "--summary-out",
        default="data_processing/processed/hard_site_candidate_recall_summary.json",
    )
    parser.add_argument(
        "--topk-candidate-out",
        default="data_processing/processed/hard_site_candidate_topk_points.csv",
        help="Long-form per-point candidate output.",
    )
    parser.add_argument(
        "--topk-summary-out",
        default="data_processing/processed/hard_site_candidate_topk_summary.csv",
        help="Site/floor Top-K oracle summary output.",
    )
    parser.add_argument(
        "--topk",
        type=int,
        default=50,
        help="Number of nearest predicted-position candidates to save per validation point.",
    )
    parser.add_argument(
        "--rerank-dataset-out",
        default="data_processing/processed/hard_site_candidate_rerank_dataset.csv",
        help="Candidate-level rerank training/diagnostic dataset output.",
    )
    parser.add_argument(
        "--rerank-summary-out",
        default="data_processing/processed/hard_site_candidate_rerank_summary.json",
        help="Rerank dataset baseline summary output.",
    )
    parser.add_argument("--include-rerank-wifi-features", action="store_true")
    parser.add_argument("--wifi-knn-topn", type=int, default=50)
    parser.add_argument("--wifi-rssi-clip-min", type=float, default=-100.0)
    parser.add_argument("--wifi-rssi-clip-max", type=float, default=-20.0)
    parser.add_argument("--include-rerank-source-wifi-features", action="store_true")
    parser.add_argument("--source-wifi-topn", type=int, default=5)
    parser.add_argument("--include-rerank-temporal-density-features", action="store_true")
    parser.add_argument("--density-radius-small", type=float, default=3.0)
    parser.add_argument("--density-radius-medium", type=float, default=5.0)
    parser.add_argument("--density-radius-large", type=float, default=10.0)
    return parser.parse_args()


def resolve_path(path_value: str) -> Path:
    path = Path(path_value)
    return path if path.is_absolute() else PROJECT_ROOT / path


def load_yaml(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"Invalid YAML payload: {path}")
    return data


def load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"Invalid JSON payload: {path}")
    return data


def load_prediction_artifact(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing absolute holdout point prediction artifact: {path}\n"
            f"Run first: {ARTIFACT_GENERATION_COMMAND}"
        )

    data = pd.read_csv(path)
    missing_columns = sorted(PREDICTION_ARTIFACT_COLUMNS - set(data.columns))
    if missing_columns:
        raise ValueError(
            f"Prediction artifact is missing required columns: {missing_columns}\n"
            f"Artifact: {path}"
        )

    text_columns = ["site_id", "path_id", "floor", "model_kind", "feature_source"]
    for column in text_columns:
        data[column] = data[column].astype(str)

    numeric_columns = ["timestamp", "point_index", "x", "y", "pred_x", "pred_y"]
    for column in numeric_columns:
        data[column] = pd.to_numeric(data[column], errors="coerce")

    if data[numeric_columns].isna().any().any():
        bad_columns = [column for column in numeric_columns if data[column].isna().any()]
        raise ValueError(f"Prediction artifact has non-numeric values in columns: {bad_columns}")

    data["timestamp"] = data["timestamp"].astype(np.int64)
    data["point_index"] = data["point_index"].astype(np.int64)
    return data


def get_path_predictions(predictions: pd.DataFrame, site_id: str, path_id: str) -> pd.DataFrame:
    path_df = predictions[
        (predictions["site_id"] == str(site_id))
        & (predictions["path_id"] == str(path_id))
    ].copy()
    if path_df.empty:
        raise ValueError(
            f"Prediction artifact has no rows for site_id={site_id}, path_id={path_id}.\n"
            f"Regenerate the artifact with matching holdout settings.\n"
            f"Run first: {ARTIFACT_GENERATION_COMMAND}"
        )
    return path_df.sort_values(["point_index", "timestamp"]).reset_index(drop=True)


def get_site_ids(args: argparse.Namespace, base_summary: dict) -> List[str]:
    if args.site_list.strip():
        return [site.strip() for site in args.site_list.split(",") if site.strip()]
    site_ids = base_summary.get("site_ids") or []
    if not site_ids:
        raise ValueError("No site_ids found in site summary source.")
    return [str(site_id) for site_id in site_ids]


def get_effective_setting(args_value, base_summary: dict, key: str, default):
    if args_value is not None:
        return args_value
    return base_summary.get(key, default)


def collect_same_floor_training_waypoints(train_files: List[Path], floor: str) -> np.ndarray:
    points: List[List[float]] = []
    for path_file in train_files:
        if path_file.parent.name != floor:
            continue
        with open(path_file, "r", encoding="utf-8") as handle:
            for line in handle:
                if not line or line.startswith("#"):
                    continue
                parts = line.rstrip("\n").split("\t")
                if len(parts) >= 4 and parts[1] == "TYPE_WAYPOINT":
                    try:
                        points.append([float(parts[2]), float(parts[3])])
                    except ValueError:
                        continue
    if not points:
        return np.zeros((0, 2), dtype=np.float64)
    return np.unique(np.round(np.asarray(points, dtype=np.float64), 1), axis=0)


def _coord_key(floor: str, x_value: float, y_value: float) -> Tuple[str, float, float]:
    return (str(floor), float(np.round(float(x_value), 1)), float(np.round(float(y_value), 1)))


def _extract_basic_wifi_matrix(
    wifi_df: pd.DataFrame,
    query_timestamps: Sequence[int],
    bssid_vocab: Sequence[str],
    window_ms: int,
    missing_value: float,
) -> np.ndarray:
    n_rows = len(query_timestamps)
    n_bssid = len(bssid_vocab)
    matrix = np.full((n_rows, n_bssid), missing_value, dtype=np.float32)
    if n_rows == 0 or n_bssid == 0 or wifi_df is None or wifi_df.empty:
        return matrix

    bssid_to_col = {bssid: idx for idx, bssid in enumerate(bssid_vocab)}
    wifi_vocab = wifi_df[wifi_df["bssid"].isin(bssid_to_col)].copy()
    if wifi_vocab.empty:
        return matrix

    wifi_vocab = wifi_vocab.sort_values("timestamp")
    wifi_ts = wifi_vocab["timestamp"].to_numpy(dtype=np.int64)
    wifi_bssid = wifi_vocab["bssid"].to_numpy()
    wifi_rssi = wifi_vocab["rssi"].to_numpy(dtype=np.float32)

    for row_index, query_ts in enumerate(np.asarray(query_timestamps, dtype=np.int64)):
        pos = np.searchsorted(wifi_ts, query_ts, side="left")
        candidate_positions: List[int] = []
        if pos > 0:
            candidate_positions.append(pos - 1)
        if pos < len(wifi_ts):
            candidate_positions.append(pos)
        if not candidate_positions:
            continue

        diffs = np.abs(wifi_ts[candidate_positions] - query_ts)
        nearest_pos = candidate_positions[int(np.argmin(diffs))]
        nearest_ts = wifi_ts[nearest_pos]
        if abs(int(nearest_ts) - int(query_ts)) > int(window_ms):
            continue

        scan_mask = wifi_ts == nearest_ts
        for bssid, rssi in zip(wifi_bssid[scan_mask], wifi_rssi[scan_mask]):
            col = bssid_to_col.get(bssid)
            if col is None:
                continue
            if matrix[row_index, col] == missing_value or rssi > matrix[row_index, col]:
                matrix[row_index, col] = rssi

    return matrix


def extract_basic_wifi_vectors_for_paths(
    path_files: Sequence[Path],
    bssid_vocab: Sequence[str],
    window_ms: int,
    missing_value: float = MISSING_WIFI_RSSI,
) -> Tuple[pd.DataFrame, np.ndarray]:
    meta_frames: List[pd.DataFrame] = []
    vector_blocks: List[np.ndarray] = []

    for path_file in path_files:
        sensor_data = read_data_file(path_file)
        if sensor_data.waypoint is None or sensor_data.waypoint.empty:
            continue

        waypoints = sensor_data.waypoint.sort_values("timestamp").reset_index(drop=True)
        timestamps = waypoints["timestamp"].to_numpy(dtype=np.int64)
        vectors = _extract_basic_wifi_matrix(
            wifi_df=sensor_data.wifi,
            query_timestamps=timestamps,
            bssid_vocab=bssid_vocab,
            window_ms=window_ms,
            missing_value=missing_value,
        )
        meta_frames.append(
            pd.DataFrame(
                {
                    "floor": path_file.parent.name,
                    "path_id": path_file.stem,
                    "timestamp": timestamps,
                    "point_index": np.arange(len(waypoints), dtype=np.int64),
                    "x": waypoints["x"].to_numpy(dtype=np.float64),
                    "y": waypoints["y"].to_numpy(dtype=np.float64),
                }
            )
        )
        vector_blocks.append(vectors)

    if not meta_frames:
        return pd.DataFrame(), np.zeros((0, len(bssid_vocab)), dtype=np.float32)

    return pd.concat(meta_frames, ignore_index=True), np.vstack(vector_blocks)


def build_candidate_wifi_index(
    train_meta: pd.DataFrame,
    train_wifi_vectors: np.ndarray,
    missing_value: float = MISSING_WIFI_RSSI,
) -> Dict[str, object]:
    if len(train_meta) != len(train_wifi_vectors):
        raise ValueError(f"WiFi train meta/vector mismatch: meta={len(train_meta)}, vectors={len(train_wifi_vectors)}")

    candidate_vectors: Dict[Tuple[str, float, float], np.ndarray] = {}
    candidate_source_count: Dict[Tuple[str, float, float], int] = {}
    candidate_visible_count: Dict[Tuple[str, float, float], int] = {}
    floor_source_vectors: Dict[str, np.ndarray] = {}
    floor_source_coord_keys: Dict[str, np.ndarray] = {}

    meta = train_meta.copy()
    meta["x_round"] = np.round(meta["x"].astype(float), 1)
    meta["y_round"] = np.round(meta["y"].astype(float), 1)
    meta["_row_index"] = np.arange(len(meta), dtype=np.int64)

    for (floor, x_round, y_round), group in meta.groupby(["floor", "x_round", "y_round"], sort=False):
        key = _coord_key(str(floor), float(x_round), float(y_round))
        row_indices = group["_row_index"].to_numpy(dtype=np.int64)
        source_vectors = train_wifi_vectors[row_indices]
        observed = source_vectors != missing_value
        if source_vectors.shape[1] == 0:
            aggregate = np.zeros((0,), dtype=np.float32)
        else:
            aggregate = np.full(source_vectors.shape[1], missing_value, dtype=np.float32)
            any_observed = observed.any(axis=0)
            if any_observed.any():
                aggregate[any_observed] = np.max(np.where(observed[:, any_observed], source_vectors[:, any_observed], missing_value), axis=0)

        candidate_vectors[key] = aggregate
        candidate_source_count[key] = int(len(row_indices))
        candidate_visible_count[key] = int(np.sum(aggregate != missing_value))

    for floor, group in meta.groupby("floor", sort=False):
        row_indices = group["_row_index"].to_numpy(dtype=np.int64)
        floor_source_vectors[str(floor)] = train_wifi_vectors[row_indices]
        floor_source_coord_keys[str(floor)] = np.asarray(
            [
                f"{np.round(float(row.x), 1):.1f}|{np.round(float(row.y), 1):.1f}"
                for row in group.itertuples(index=False)
            ],
            dtype=object,
        )

    return {
        "candidate_vectors": candidate_vectors,
        "candidate_source_count": candidate_source_count,
        "candidate_visible_count": candidate_visible_count,
        "floor_source_vectors": floor_source_vectors,
        "floor_source_coord_keys": floor_source_coord_keys,
    }


def build_candidate_wifi_source_index(
    train_meta: pd.DataFrame,
    train_wifi_vectors: np.ndarray,
    missing_value: float = MISSING_WIFI_RSSI,
) -> Dict[str, object]:
    if len(train_meta) != len(train_wifi_vectors):
        raise ValueError(f"WiFi train source meta/vector mismatch: meta={len(train_meta)}, vectors={len(train_wifi_vectors)}")

    candidate_source_vectors: Dict[Tuple[str, float, float], np.ndarray] = {}
    candidate_source_count: Dict[Tuple[str, float, float], int] = {}
    floor_source_vectors: Dict[str, np.ndarray] = {}
    floor_source_coord_keys: Dict[str, np.ndarray] = {}

    meta = train_meta.copy()
    meta["x_round"] = np.round(meta["x"].astype(float), 1)
    meta["y_round"] = np.round(meta["y"].astype(float), 1)
    meta["_row_index"] = np.arange(len(meta), dtype=np.int64)

    for (floor, x_round, y_round), group in meta.groupby(["floor", "x_round", "y_round"], sort=False):
        key = _coord_key(str(floor), float(x_round), float(y_round))
        row_indices = group["_row_index"].to_numpy(dtype=np.int64)
        candidate_source_vectors[key] = train_wifi_vectors[row_indices]
        candidate_source_count[key] = int(len(row_indices))

    for floor, group in meta.groupby("floor", sort=False):
        row_indices = group["_row_index"].to_numpy(dtype=np.int64)
        floor_source_vectors[str(floor)] = train_wifi_vectors[row_indices]
        floor_source_coord_keys[str(floor)] = np.asarray(
            [
                f"{np.round(float(row.x), 1):.1f}|{np.round(float(row.y), 1):.1f}"
                for row in group.itertuples(index=False)
            ],
            dtype=object,
        )

    return {
        "candidate_source_vectors": candidate_source_vectors,
        "candidate_source_count": candidate_source_count,
        "floor_source_vectors": floor_source_vectors,
        "floor_source_coord_keys": floor_source_coord_keys,
    }


def compute_wifi_similarity_features(
    validation_vector: np.ndarray,
    candidate_vector: np.ndarray,
    rssi_clip_min: float,
    rssi_clip_max: float,
    missing_value: float = MISSING_WIFI_RSSI,
) -> Dict[str, float]:
    validation_observed = validation_vector != missing_value
    candidate_observed = candidate_vector != missing_value
    common_mask = validation_observed & candidate_observed
    union_mask = validation_observed | candidate_observed

    common_count = int(np.sum(common_mask))
    union_count = int(np.sum(union_mask))
    validation_visible_count = int(np.sum(validation_observed))
    candidate_visible_count = int(np.sum(candidate_observed))

    validation_strength = np.zeros_like(validation_vector, dtype=np.float64)
    candidate_strength = np.zeros_like(candidate_vector, dtype=np.float64)
    if validation_vector.size:
        validation_strength[validation_observed] = (
            np.clip(validation_vector[validation_observed], rssi_clip_min, rssi_clip_max) - rssi_clip_min
        ) / max(rssi_clip_max - rssi_clip_min, 1e-12)
        candidate_strength[candidate_observed] = (
            np.clip(candidate_vector[candidate_observed], rssi_clip_min, rssi_clip_max) - rssi_clip_min
        ) / max(rssi_clip_max - rssi_clip_min, 1e-12)

    denom = float(np.linalg.norm(validation_strength) * np.linalg.norm(candidate_strength))
    cosine_similarity = float(np.dot(validation_strength, candidate_strength) / denom) if denom > 0.0 else 0.0

    if common_count == 0:
        return {
            "wifi_common_bssid_count": 0,
            "wifi_union_bssid_count": union_count,
            "wifi_jaccard_similarity": 0.0,
            "wifi_rssi_l1_distance_on_common": float("nan"),
            "wifi_rssi_l2_distance_on_common": float("nan"),
            "wifi_cosine_similarity": cosine_similarity,
            "wifi_weighted_overlap_score": 0.0,
            "candidate_wifi_visible_bssid_count": candidate_visible_count,
            "validation_wifi_visible_bssid_count": validation_visible_count,
            "wifi_has_common_bssid": 0,
        }

    validation_common = np.clip(validation_vector[common_mask], rssi_clip_min, rssi_clip_max).astype(np.float64)
    candidate_common = np.clip(candidate_vector[common_mask], rssi_clip_min, rssi_clip_max).astype(np.float64)
    diff = validation_common - candidate_common
    l1_distance = float(np.mean(np.abs(diff)))
    l2_distance = float(np.sqrt(np.mean(diff * diff)))
    jaccard_similarity = float(common_count / max(union_count, 1))
    weighted_overlap_score = float(jaccard_similarity * np.exp(-l1_distance / 10.0))

    return {
        "wifi_common_bssid_count": common_count,
        "wifi_union_bssid_count": union_count,
        "wifi_jaccard_similarity": jaccard_similarity,
        "wifi_rssi_l1_distance_on_common": l1_distance,
        "wifi_rssi_l2_distance_on_common": l2_distance,
        "wifi_cosine_similarity": cosine_similarity,
        "wifi_weighted_overlap_score": weighted_overlap_score,
        "candidate_wifi_visible_bssid_count": candidate_visible_count,
        "validation_wifi_visible_bssid_count": validation_visible_count,
        "wifi_has_common_bssid": 1,
    }


def _weighted_overlap_scores_to_sources(
    validation_vector: np.ndarray,
    source_vectors: np.ndarray,
    rssi_clip_min: float,
    rssi_clip_max: float,
    missing_value: float,
) -> np.ndarray:
    if source_vectors.size == 0 or validation_vector.size == 0:
        return np.zeros(len(source_vectors), dtype=np.float64)

    validation_observed = validation_vector != missing_value
    if not validation_observed.any():
        return np.zeros(len(source_vectors), dtype=np.float64)

    source_observed = source_vectors != missing_value
    common_mask = source_observed & validation_observed
    common_count = common_mask.sum(axis=1).astype(np.float64)
    union_count = source_observed.sum(axis=1).astype(np.float64) + float(validation_observed.sum()) - common_count

    validation_clipped = np.clip(validation_vector, rssi_clip_min, rssi_clip_max).astype(np.float32)
    source_clipped = np.clip(source_vectors, rssi_clip_min, rssi_clip_max).astype(np.float32)
    diff = np.abs(source_clipped - validation_clipped)
    diff[~common_mask] = 0.0
    l1_distance = diff.sum(axis=1) / np.maximum(common_count, 1.0)
    jaccard_similarity = common_count / np.maximum(union_count, 1.0)
    scores = jaccard_similarity * np.exp(-l1_distance / 10.0)
    scores[common_count == 0] = 0.0
    return scores.astype(np.float64)


def compute_source_row_wifi_similarity_features(
    validation_vector: np.ndarray,
    candidate_source_vectors: np.ndarray,
    source_wifi_topn: int,
    rssi_clip_min: float,
    rssi_clip_max: float,
    missing_value: float = MISSING_WIFI_RSSI,
) -> Dict[str, float]:
    if source_wifi_topn < 5:
        raise ValueError(f"--source-wifi-topn must be at least 5 to produce top5 features: {source_wifi_topn}")
    if len(candidate_source_vectors) == 0:
        raise ValueError("Candidate coordinate has no WiFi source rows.")

    source_count = int(len(candidate_source_vectors))
    validation_observed = validation_vector != missing_value
    validation_visible_count = int(np.sum(validation_observed))
    source_observed = candidate_source_vectors != missing_value
    common_mask = source_observed & validation_observed
    common_count = common_mask.sum(axis=1).astype(np.float64)
    source_visible_count = source_observed.sum(axis=1).astype(np.float64)
    union_count = source_visible_count + float(validation_visible_count) - common_count

    scores = np.zeros(source_count, dtype=np.float64)
    l1_distance = np.full(source_count, np.nan, dtype=np.float64)
    cosine_similarity = np.zeros(source_count, dtype=np.float64)

    if validation_visible_count > 0 and validation_vector.size:
        validation_clipped = np.clip(validation_vector, rssi_clip_min, rssi_clip_max).astype(np.float64)
        source_clipped = np.clip(candidate_source_vectors, rssi_clip_min, rssi_clip_max).astype(np.float64)

        diff = np.abs(source_clipped - validation_clipped)
        diff[~common_mask] = 0.0
        has_common = common_count > 0.0
        l1_distance[has_common] = diff[has_common].sum(axis=1) / common_count[has_common]
        jaccard_similarity = np.zeros(source_count, dtype=np.float64)
        jaccard_similarity[has_common] = common_count[has_common] / np.maximum(union_count[has_common], 1.0)
        scores[has_common] = jaccard_similarity[has_common] * np.exp(-l1_distance[has_common] / 10.0)

        validation_strength = np.zeros_like(validation_vector, dtype=np.float64)
        validation_strength[validation_observed] = (
            validation_clipped[validation_observed] - rssi_clip_min
        ) / max(rssi_clip_max - rssi_clip_min, 1e-12)
        source_strength = np.zeros_like(candidate_source_vectors, dtype=np.float64)
        source_strength[source_observed] = (
            source_clipped[source_observed] - rssi_clip_min
        ) / max(rssi_clip_max - rssi_clip_min, 1e-12)
        validation_norm = float(np.linalg.norm(validation_strength))
        source_norm = np.linalg.norm(source_strength, axis=1)
        denom = source_norm * validation_norm
        valid_cosine = denom > 0.0
        cosine_similarity[valid_cosine] = source_strength[valid_cosine].dot(validation_strength) / denom[valid_cosine]

    source_order = np.lexsort((np.arange(source_count, dtype=np.int64), np.nan_to_num(l1_distance, nan=np.inf), -scores))
    top3_order = source_order[: min(3, source_count)]
    top5_order = source_order[: min(5, source_count)]
    finite_l1 = l1_distance[np.isfinite(l1_distance)]
    top3_l1 = l1_distance[top3_order]
    top3_l1 = top3_l1[np.isfinite(top3_l1)]

    return {
        "candidate_wifi_source_count": source_count,
        "candidate_wifi_best_source_score": float(np.max(scores)) if source_count else 0.0,
        "candidate_wifi_top3_source_score_mean": float(np.mean(scores[top3_order])) if len(top3_order) else 0.0,
        "candidate_wifi_top3_source_score_max": float(np.max(scores[top3_order])) if len(top3_order) else 0.0,
        "candidate_wifi_top5_source_score_mean": float(np.mean(scores[top5_order])) if len(top5_order) else 0.0,
        "candidate_wifi_source_score_std": float(np.std(scores)) if source_count else 0.0,
        "candidate_wifi_source_score_p90": float(np.quantile(scores, 0.9)) if source_count else 0.0,
        "candidate_wifi_best_source_l1": float(np.min(finite_l1)) if len(finite_l1) else float("nan"),
        "candidate_wifi_top3_source_l1_mean": float(np.mean(top3_l1)) if len(top3_l1) else float("nan"),
        "candidate_wifi_best_source_cosine": float(np.max(cosine_similarity)) if source_count else 0.0,
        "candidate_wifi_top3_source_cosine_mean": float(np.mean(cosine_similarity[top3_order])) if len(top3_order) else 0.0,
        "candidate_wifi_best_common_bssid_count": int(np.max(common_count)) if source_count else 0,
        "candidate_wifi_top3_common_bssid_mean": float(np.mean(common_count[top3_order])) if len(top3_order) else 0.0,
        "source_wifi_validation_visible_bssid_count": validation_visible_count,
        "source_wifi_has_common_bssid": int(np.max(common_count) > 0.0) if source_count else 0,
    }


def attach_wifi_features_to_rerank_dataset(
    rerank_df: pd.DataFrame,
    site_ids: Sequence[str],
    train_dir: Path,
    n_bssid: int,
    window_ms: int,
    holdout_fraction: float,
    seed: int,
    max_holdout_paths: int,
    wifi_knn_topn: int,
    rssi_clip_min: float,
    rssi_clip_max: float,
    missing_value: float = MISSING_WIFI_RSSI,
) -> pd.DataFrame:
    if rssi_clip_min >= rssi_clip_max:
        raise ValueError(f"Invalid WiFi RSSI clip range: min={rssi_clip_min}, max={rssi_clip_max}")

    data = rerank_df.copy()
    data["_row_id"] = np.arange(len(data), dtype=np.int64)
    feature_rows: List[Dict[str, object]] = []

    for site_index, site_id in enumerate(site_ids, start=1):
        site_mask = data["site_id"].astype(str) == str(site_id)
        site_data = data[site_mask]
        if site_data.empty:
            continue

        path_files = list_site_paths(train_dir / str(site_id))
        train_files, holdout_files = split_holdout_paths(
            path_files=path_files,
            holdout_fraction=holdout_fraction,
            seed=seed + site_index,
            max_holdout_paths=max_holdout_paths,
        )
        bssid_vocab = build_vocab_from_files(train_files, n_bssid=n_bssid)
        train_wifi_meta, train_wifi_vectors = extract_basic_wifi_vectors_for_paths(
            path_files=train_files,
            bssid_vocab=bssid_vocab,
            window_ms=window_ms,
            missing_value=missing_value,
        )
        holdout_wifi_meta, holdout_wifi_vectors = extract_basic_wifi_vectors_for_paths(
            path_files=holdout_files,
            bssid_vocab=bssid_vocab,
            window_ms=window_ms,
            missing_value=missing_value,
        )
        candidate_wifi_index = build_candidate_wifi_index(
            train_meta=train_wifi_meta,
            train_wifi_vectors=train_wifi_vectors,
            missing_value=missing_value,
        )

        validation_vectors: Dict[Tuple[str, int, int], np.ndarray] = {}
        for row_index, row in holdout_wifi_meta.reset_index(drop=True).iterrows():
            validation_vectors[(str(row["path_id"]), int(row["timestamp"]), int(row["point_index"]))] = holdout_wifi_vectors[row_index]

        for group_id, group in site_data.groupby("group_id", sort=False):
            first = group.iloc[0]
            validation_key = (str(first["path_id"]), int(first["timestamp"]), int(first["point_index"]))
            validation_vector = validation_vectors.get(validation_key)
            if validation_vector is None:
                raise ValueError(f"Missing validation WiFi vector for group {group_id}")

            floor = str(first["floor"])
            source_vectors = candidate_wifi_index["floor_source_vectors"].get(floor)
            source_coord_keys = candidate_wifi_index["floor_source_coord_keys"].get(floor)
            if source_vectors is None or source_coord_keys is None:
                raise ValueError(f"Missing same-floor WiFi source rows for site={site_id}, floor={floor}")

            source_scores = _weighted_overlap_scores_to_sources(
                validation_vector=validation_vector,
                source_vectors=source_vectors,
                rssi_clip_min=rssi_clip_min,
                rssi_clip_max=rssi_clip_max,
                missing_value=missing_value,
            )
            if source_scores.size and np.max(source_scores) > 0.0:
                source_order = np.argsort(-source_scores, kind="mergesort")
                top_source_keys = source_coord_keys[source_order[: max(int(wifi_knn_topn), 50)]]
            else:
                top_source_keys = np.asarray([], dtype=object)

            group_feature_rows: List[Dict[str, object]] = []
            for _, row in group.iterrows():
                candidate_key = _coord_key(str(row["floor"]), float(row["candidate_x"]), float(row["candidate_y"]))
                candidate_vector = candidate_wifi_index["candidate_vectors"].get(candidate_key)
                if candidate_vector is None:
                    raise ValueError(
                        "Could not map candidate coordinate to train WiFi fingerprint: "
                        f"site={site_id}, floor={candidate_key[0]}, x={candidate_key[1]}, y={candidate_key[2]}"
                    )

                candidate_features = compute_wifi_similarity_features(
                    validation_vector=validation_vector,
                    candidate_vector=candidate_vector,
                    rssi_clip_min=rssi_clip_min,
                    rssi_clip_max=rssi_clip_max,
                    missing_value=missing_value,
                )
                candidate_coord_key = f"{candidate_key[1]:.1f}|{candidate_key[2]:.1f}"
                candidate_features.update(
                    {
                        "_row_id": int(row["_row_id"]),
                        "candidate_wifi_source_count": int(candidate_wifi_index["candidate_source_count"][candidate_key]),
                        "same_floor_wifi_neighbor_count_top10": int(np.sum(top_source_keys[:10] == candidate_coord_key)),
                        "same_floor_wifi_neighbor_count_top20": int(np.sum(top_source_keys[:20] == candidate_coord_key)),
                        "same_floor_wifi_neighbor_count_top50": int(np.sum(top_source_keys[:50] == candidate_coord_key)),
                    }
                )
                group_feature_rows.append(candidate_features)

            group_features = pd.DataFrame(group_feature_rows)
            group_features["_wifi_l1_sort"] = group_features["wifi_rssi_l1_distance_on_common"].fillna(np.inf)
            group_features = group_features.sort_values(
                ["wifi_weighted_overlap_score", "_wifi_l1_sort", "_row_id"],
                ascending=[False, True, True],
            ).reset_index(drop=True)
            group_features["candidate_wifi_knn_rank_within_point"] = np.arange(1, len(group_features) + 1, dtype=np.int64)
            group_features["candidate_wifi_knn_score"] = group_features["wifi_weighted_overlap_score"].astype(np.float64)
            feature_rows.extend(group_features.drop(columns=["_wifi_l1_sort"]).to_dict(orient="records"))

    feature_df = pd.DataFrame(feature_rows)
    if len(feature_df) != len(data):
        raise ValueError(f"WiFi feature row mismatch: features={len(feature_df)}, rerank_rows={len(data)}")

    data = data.merge(feature_df, on="_row_id", how="left")
    if data["candidate_wifi_source_count"].isna().any():
        raise ValueError("Missing WiFi features for at least one rerank row.")
    return data.drop(columns=["_row_id"]).reset_index(drop=True)


def attach_source_wifi_features_to_rerank_dataset(
    rerank_df: pd.DataFrame,
    site_ids: Sequence[str],
    train_dir: Path,
    n_bssid: int,
    window_ms: int,
    holdout_fraction: float,
    seed: int,
    max_holdout_paths: int,
    source_wifi_topn: int,
    rssi_clip_min: float,
    rssi_clip_max: float,
    include_aggregate_wifi_features: bool = False,
    wifi_knn_topn: int = 50,
    missing_value: float = MISSING_WIFI_RSSI,
) -> pd.DataFrame:
    if rssi_clip_min >= rssi_clip_max:
        raise ValueError(f"Invalid WiFi RSSI clip range: min={rssi_clip_min}, max={rssi_clip_max}")
    if source_wifi_topn < 5:
        raise ValueError(f"--source-wifi-topn must be at least 5: {source_wifi_topn}")

    data = rerank_df.copy()
    data["_row_id"] = np.arange(len(data), dtype=np.int64)
    feature_rows: List[Dict[str, object]] = []

    for site_index, site_id in enumerate(site_ids, start=1):
        site_mask = data["site_id"].astype(str) == str(site_id)
        site_data = data[site_mask]
        if site_data.empty:
            continue

        path_files = list_site_paths(train_dir / str(site_id))
        train_files, holdout_files = split_holdout_paths(
            path_files=path_files,
            holdout_fraction=holdout_fraction,
            seed=seed + site_index,
            max_holdout_paths=max_holdout_paths,
        )
        bssid_vocab = build_vocab_from_files(train_files, n_bssid=n_bssid)
        train_wifi_meta, train_wifi_vectors = extract_basic_wifi_vectors_for_paths(
            path_files=train_files,
            bssid_vocab=bssid_vocab,
            window_ms=window_ms,
            missing_value=missing_value,
        )
        holdout_wifi_meta, holdout_wifi_vectors = extract_basic_wifi_vectors_for_paths(
            path_files=holdout_files,
            bssid_vocab=bssid_vocab,
            window_ms=window_ms,
            missing_value=missing_value,
        )
        candidate_source_index = build_candidate_wifi_source_index(
            train_meta=train_wifi_meta,
            train_wifi_vectors=train_wifi_vectors,
            missing_value=missing_value,
        )
        candidate_wifi_index = (
            build_candidate_wifi_index(
                train_meta=train_wifi_meta,
                train_wifi_vectors=train_wifi_vectors,
                missing_value=missing_value,
            )
            if include_aggregate_wifi_features
            else None
        )

        validation_vectors: Dict[Tuple[str, int, int], np.ndarray] = {}
        for row_index, row in holdout_wifi_meta.reset_index(drop=True).iterrows():
            validation_vectors[(str(row["path_id"]), int(row["timestamp"]), int(row["point_index"]))] = holdout_wifi_vectors[row_index]

        for group_id, group in site_data.groupby("group_id", sort=False):
            first = group.iloc[0]
            validation_key = (str(first["path_id"]), int(first["timestamp"]), int(first["point_index"]))
            validation_vector = validation_vectors.get(validation_key)
            if validation_vector is None:
                raise ValueError(f"Missing validation WiFi vector for group {group_id}")

            top_source_keys = np.asarray([], dtype=object)
            if include_aggregate_wifi_features:
                floor = str(first["floor"])
                source_vectors = candidate_source_index["floor_source_vectors"].get(floor)
                source_coord_keys = candidate_source_index["floor_source_coord_keys"].get(floor)
                if source_vectors is None or source_coord_keys is None:
                    raise ValueError(f"Missing same-floor WiFi source rows for site={site_id}, floor={floor}")

                source_scores = _weighted_overlap_scores_to_sources(
                    validation_vector=validation_vector,
                    source_vectors=source_vectors,
                    rssi_clip_min=rssi_clip_min,
                    rssi_clip_max=rssi_clip_max,
                    missing_value=missing_value,
                )
                if source_scores.size and np.max(source_scores) > 0.0:
                    source_order = np.argsort(-source_scores, kind="mergesort")
                    top_source_keys = source_coord_keys[source_order[: max(int(wifi_knn_topn), 50)]]

            group_feature_rows: List[Dict[str, object]] = []
            for _, row in group.iterrows():
                candidate_key = _coord_key(str(row["floor"]), float(row["candidate_x"]), float(row["candidate_y"]))
                candidate_source_vectors = candidate_source_index["candidate_source_vectors"].get(candidate_key)
                if candidate_source_vectors is None or len(candidate_source_vectors) == 0:
                    raise ValueError(
                        "Could not map candidate coordinate to train WiFi source rows: "
                        f"site={site_id}, floor={candidate_key[0]}, x={candidate_key[1]}, y={candidate_key[2]}"
                    )

                candidate_features = compute_source_row_wifi_similarity_features(
                    validation_vector=validation_vector,
                    candidate_source_vectors=candidate_source_vectors,
                    source_wifi_topn=int(source_wifi_topn),
                    rssi_clip_min=rssi_clip_min,
                    rssi_clip_max=rssi_clip_max,
                    missing_value=missing_value,
                )
                candidate_features.update(
                    {
                        "_row_id": int(row["_row_id"]),
                        "_rank_sort": int(row["rank"]),
                    }
                )

                if include_aggregate_wifi_features:
                    if candidate_wifi_index is None:
                        raise ValueError("Internal error: aggregate WiFi index was not built.")
                    candidate_vector = candidate_wifi_index["candidate_vectors"].get(candidate_key)
                    if candidate_vector is None:
                        raise ValueError(
                            "Could not map candidate coordinate to train WiFi fingerprint: "
                            f"site={site_id}, floor={candidate_key[0]}, x={candidate_key[1]}, y={candidate_key[2]}"
                        )

                    aggregate_features = compute_wifi_similarity_features(
                        validation_vector=validation_vector,
                        candidate_vector=candidate_vector,
                        rssi_clip_min=rssi_clip_min,
                        rssi_clip_max=rssi_clip_max,
                        missing_value=missing_value,
                    )
                    candidate_coord_key = f"{candidate_key[1]:.1f}|{candidate_key[2]:.1f}"
                    aggregate_features.update(
                        {
                            "candidate_wifi_source_count": int(candidate_wifi_index["candidate_source_count"][candidate_key]),
                            "same_floor_wifi_neighbor_count_top10": int(np.sum(top_source_keys[:10] == candidate_coord_key)),
                            "same_floor_wifi_neighbor_count_top20": int(np.sum(top_source_keys[:20] == candidate_coord_key)),
                            "same_floor_wifi_neighbor_count_top50": int(np.sum(top_source_keys[:50] == candidate_coord_key)),
                        }
                    )
                    candidate_features.update(aggregate_features)

                group_feature_rows.append(candidate_features)

            group_features = pd.DataFrame(group_feature_rows)
            if include_aggregate_wifi_features:
                group_features["_wifi_l1_sort"] = group_features["wifi_rssi_l1_distance_on_common"].fillna(np.inf)
                aggregate_ranked = group_features.sort_values(
                    ["wifi_weighted_overlap_score", "_wifi_l1_sort", "_row_id"],
                    ascending=[False, True, True],
                ).reset_index(drop=True)
                aggregate_ranked["candidate_wifi_knn_rank_within_point"] = np.arange(1, len(aggregate_ranked) + 1, dtype=np.int64)
                group_features = group_features.merge(
                    aggregate_ranked[["_row_id", "candidate_wifi_knn_rank_within_point"]],
                    on="_row_id",
                    how="left",
                )
                group_features["candidate_wifi_knn_score"] = group_features["wifi_weighted_overlap_score"].astype(np.float64)

            source_rank_specs = [
                ("source_wifi_best_score_rank_within_point", "candidate_wifi_best_source_score", False),
                ("source_wifi_top3_score_rank_within_point", "candidate_wifi_top3_source_score_mean", False),
                ("source_wifi_best_l1_rank_within_point", "candidate_wifi_best_source_l1", True),
                ("source_wifi_best_cosine_rank_within_point", "candidate_wifi_best_source_cosine", False),
            ]
            for output_column, sort_column, ascending in source_rank_specs:
                ranked = group_features.sort_values(
                    [sort_column, "_rank_sort", "_row_id"],
                    ascending=[ascending, True, True],
                    na_position="last",
                ).reset_index(drop=True)
                ranked[output_column] = np.arange(1, len(ranked) + 1, dtype=np.int64)
                group_features = group_features.merge(ranked[["_row_id", output_column]], on="_row_id", how="left")

            drop_columns = [column for column in ["_wifi_l1_sort", "_rank_sort"] if column in group_features.columns]
            feature_rows.extend(group_features.drop(columns=drop_columns).to_dict(orient="records"))

    feature_df = pd.DataFrame(feature_rows)
    if len(feature_df) != len(data):
        raise ValueError(f"Source WiFi feature row mismatch: features={len(feature_df)}, rerank_rows={len(data)}")

    if "candidate_wifi_source_count" in data.columns and "candidate_wifi_source_count" in feature_df.columns:
        existing_counts = data[["_row_id", "candidate_wifi_source_count"]].merge(
            feature_df[["_row_id", "candidate_wifi_source_count"]],
            on="_row_id",
            how="inner",
            suffixes=("_existing", "_source"),
        )
        if not np.allclose(
            existing_counts["candidate_wifi_source_count_existing"].to_numpy(dtype=np.float64),
            existing_counts["candidate_wifi_source_count_source"].to_numpy(dtype=np.float64),
            rtol=0.0,
            atol=0.0,
        ):
            raise ValueError("Existing aggregate candidate_wifi_source_count does not match source-row index counts.")
        feature_df = feature_df.drop(columns=["candidate_wifi_source_count"])

    data = data.merge(feature_df, on="_row_id", how="left")
    if data["candidate_wifi_best_source_score"].isna().any():
        raise ValueError("Missing source WiFi features for at least one rerank row.")
    return data.drop(columns=["_row_id"]).reset_index(drop=True)


def _distance_to_columns(data: pd.DataFrame, x_column: str, y_column: str) -> np.ndarray:
    candidate_xy = data[["candidate_x", "candidate_y"]].to_numpy(dtype=np.float64)
    target_xy = data[[x_column, y_column]].to_numpy(dtype=np.float64)
    valid = np.isfinite(target_xy).all(axis=1)
    distances = np.full(len(data), np.nan, dtype=np.float64)
    distances[valid] = np.linalg.norm(candidate_xy[valid] - target_xy[valid], axis=1)
    return distances


def attach_temporal_features_to_rerank_dataset(rerank_df: pd.DataFrame) -> pd.DataFrame:
    required_columns = {
        "site_id",
        "path_id",
        "floor",
        "timestamp",
        "point_index",
        "group_id",
        "rank",
        "pred_x",
        "pred_y",
        "candidate_x",
        "candidate_y",
    }
    missing_columns = sorted(required_columns - set(rerank_df.columns))
    if missing_columns:
        raise ValueError(f"Rerank dataset is missing temporal feature columns: {missing_columns}")

    data = rerank_df.copy()
    data["_row_id"] = np.arange(len(data), dtype=np.int64)
    point_columns = ["site_id", "path_id", "floor", "timestamp", "point_index", "group_id", "pred_x", "pred_y"]
    points = data[point_columns].drop_duplicates("group_id").copy()
    if len(points) != int(data["group_id"].nunique()):
        raise ValueError("Temporal feature build expected exactly one point row per group_id.")

    rank1 = (
        data[data["rank"].astype(int) == 1][["group_id", "candidate_x", "candidate_y"]]
        .drop_duplicates("group_id")
        .rename(columns={"candidate_x": "_rank1_x", "candidate_y": "_rank1_y"})
    )
    if len(rank1) != len(points):
        raise ValueError(f"Temporal feature build expected one rank-1 candidate per group: rank1={len(rank1)}, groups={len(points)}")

    points = points.merge(rank1, on="group_id", how="left")
    feature_frames: List[pd.DataFrame] = []
    for _, path_points in points.groupby(["site_id", "path_id", "floor"], sort=False):
        path_points = path_points.sort_values(["timestamp", "point_index", "group_id"]).reset_index(drop=True)
        n_points = len(path_points)
        pred_xy = path_points[["pred_x", "pred_y"]].to_numpy(dtype=np.float64)
        rank1_xy = path_points[["_rank1_x", "_rank1_y"]].to_numpy(dtype=np.float64)

        prev_pred = np.full((n_points, 2), np.nan, dtype=np.float64)
        next_pred = np.full((n_points, 2), np.nan, dtype=np.float64)
        prev_rank1 = np.full((n_points, 2), np.nan, dtype=np.float64)
        next_rank1 = np.full((n_points, 2), np.nan, dtype=np.float64)
        if n_points > 1:
            prev_pred[1:] = pred_xy[:-1]
            next_pred[:-1] = pred_xy[1:]
            prev_rank1[1:] = rank1_xy[:-1]
            next_rank1[:-1] = rank1_xy[1:]

        raw_step_from_prev = np.full(n_points, np.nan, dtype=np.float64)
        raw_step_to_next = np.full(n_points, np.nan, dtype=np.float64)
        if n_points > 1:
            raw_step_from_prev[1:] = np.linalg.norm(pred_xy[1:] - pred_xy[:-1], axis=1)
            raw_step_to_next[:-1] = np.linalg.norm(pred_xy[1:] - pred_xy[:-1], axis=1)

        timestamps = path_points["timestamp"].to_numpy(dtype=np.float64)
        point_indices = path_points["point_index"].to_numpy(dtype=np.float64)
        timestamp_range = float(np.max(timestamps) - np.min(timestamps)) if n_points else 0.0
        point_index_range = float(np.max(point_indices) - np.min(point_indices)) if n_points else 0.0
        timestamp_norm = (timestamps - np.min(timestamps)) / timestamp_range if timestamp_range > 0.0 else np.zeros(n_points, dtype=np.float64)
        point_index_norm = (
            (point_indices - np.min(point_indices)) / point_index_range
            if point_index_range > 0.0
            else np.zeros(n_points, dtype=np.float64)
        )

        feature_frame = path_points[["group_id"]].copy()
        feature_frame["raw_pred_step_from_prev_m"] = raw_step_from_prev
        feature_frame["raw_pred_step_to_next_m"] = raw_step_to_next
        feature_frame["_prev_pred_x"] = prev_pred[:, 0]
        feature_frame["_prev_pred_y"] = prev_pred[:, 1]
        feature_frame["_next_pred_x"] = next_pred[:, 0]
        feature_frame["_next_pred_y"] = next_pred[:, 1]
        feature_frame["_prev_rank1_x"] = prev_rank1[:, 0]
        feature_frame["_prev_rank1_y"] = prev_rank1[:, 1]
        feature_frame["_next_rank1_x"] = next_rank1[:, 0]
        feature_frame["_next_rank1_y"] = next_rank1[:, 1]
        feature_frame["timestamp_norm_in_path"] = timestamp_norm
        feature_frame["point_index_norm_in_path"] = point_index_norm
        feature_frames.append(feature_frame)

    temporal_features = pd.concat(feature_frames, ignore_index=True)
    data = data.merge(temporal_features, on="group_id", how="left")
    if data["timestamp_norm_in_path"].isna().any() or data["point_index_norm_in_path"].isna().any():
        raise ValueError("Temporal feature build produced missing path normalization values.")

    data["candidate_step_from_prev_rank1_m"] = _distance_to_columns(data, "_prev_rank1_x", "_prev_rank1_y")
    data["candidate_step_to_next_rank1_m"] = _distance_to_columns(data, "_next_rank1_x", "_next_rank1_y")
    data["candidate_distance_to_prev_raw_pred_m"] = _distance_to_columns(data, "_prev_pred_x", "_prev_pred_y")
    data["candidate_distance_to_next_raw_pred_m"] = _distance_to_columns(data, "_next_pred_x", "_next_pred_y")

    smoothness_values = data[["candidate_step_from_prev_rank1_m", "candidate_step_to_next_rank1_m"]].to_numpy(dtype=np.float64)
    smoothness_counts = np.isfinite(smoothness_values).sum(axis=1)
    data["candidate_temporal_smoothness_rank1_m"] = np.where(
        smoothness_counts > 0,
        np.nansum(smoothness_values, axis=1) / np.maximum(smoothness_counts, 1),
        np.nan,
    )

    helper_columns = [
        "_row_id",
        "_prev_pred_x",
        "_prev_pred_y",
        "_next_pred_x",
        "_next_pred_y",
        "_prev_rank1_x",
        "_prev_rank1_y",
        "_next_rank1_x",
        "_next_rank1_y",
    ]
    return data.sort_values("_row_id").drop(columns=helper_columns).reset_index(drop=True)


def build_local_waypoint_density_index(
    rerank_df: pd.DataFrame,
    density_radius_small: float = 3.0,
    density_radius_medium: float = 5.0,
    density_radius_large: float = 10.0,
) -> Dict[Tuple[str, str, float, float], Dict[str, float]]:
    if min(density_radius_small, density_radius_medium, density_radius_large) <= 0.0:
        raise ValueError(
            "Density radii must be positive: "
            f"small={density_radius_small}, medium={density_radius_medium}, large={density_radius_large}"
        )
    if not (density_radius_small <= density_radius_medium <= density_radius_large):
        raise ValueError(
            "Density radii must be ordered small <= medium <= large: "
            f"small={density_radius_small}, medium={density_radius_medium}, large={density_radius_large}"
        )

    required_columns = {"site_id", "floor", "candidate_x", "candidate_y"}
    missing_columns = sorted(required_columns - set(rerank_df.columns))
    if missing_columns:
        raise ValueError(f"Rerank dataset is missing density feature columns: {missing_columns}")

    coordinates = rerank_df[["site_id", "floor", "candidate_x", "candidate_y"]].copy()
    coordinates["site_id"] = coordinates["site_id"].astype(str)
    coordinates["floor"] = coordinates["floor"].astype(str)
    coordinates["candidate_x_round"] = np.round(coordinates["candidate_x"].astype(np.float64), 1)
    coordinates["candidate_y_round"] = np.round(coordinates["candidate_y"].astype(np.float64), 1)
    coordinates = coordinates[["site_id", "floor", "candidate_x_round", "candidate_y_round"]].drop_duplicates().reset_index(drop=True)

    density_index: Dict[Tuple[str, str, float, float], Dict[str, float]] = {}
    for (site_id, floor), floor_coordinates in coordinates.groupby(["site_id", "floor"], sort=False):
        xy = floor_coordinates[["candidate_x_round", "candidate_y_round"]].to_numpy(dtype=np.float64)
        for local_index, row in enumerate(floor_coordinates.itertuples(index=False)):
            if len(xy) <= 1:
                distances = np.asarray([], dtype=np.float64)
            else:
                distances = np.linalg.norm(xy - xy[local_index], axis=1)
                distances = np.delete(distances, local_index)
                distances = np.sort(distances)

            count_small = int(np.sum(distances <= float(density_radius_small)))
            count_medium = int(np.sum(distances <= float(density_radius_medium)))
            count_large = int(np.sum(distances <= float(density_radius_large)))
            nearest_dist = float(distances[0]) if len(distances) else float("nan")
            mean_5nn = float(np.mean(distances[: min(5, len(distances))])) if len(distances) else float("nan")
            mean_10nn = float(np.mean(distances[: min(10, len(distances))])) if len(distances) else float("nan")
            key = (
                str(site_id),
                str(floor),
                float(row.candidate_x_round),
                float(row.candidate_y_round),
            )
            density_index[key] = {
                "local_waypoint_count_3m": count_small,
                "local_waypoint_count_5m": count_medium,
                "local_waypoint_count_10m": count_large,
                "local_waypoint_nearest_dist_m": nearest_dist,
                "local_waypoint_mean_dist_5nn_m": mean_5nn,
                "local_waypoint_mean_dist_10nn_m": mean_10nn,
                "candidate_is_sparse_area": int(count_medium == 0),
            }

    return density_index


def attach_local_density_features_to_rerank_dataset(
    rerank_df: pd.DataFrame,
    density_index: Dict[Tuple[str, str, float, float], Dict[str, float]] | None = None,
) -> pd.DataFrame:
    required_columns = {"site_id", "floor", "group_id", "rank", "candidate_x", "candidate_y"}
    missing_columns = sorted(required_columns - set(rerank_df.columns))
    if missing_columns:
        raise ValueError(f"Rerank dataset is missing local density attachment columns: {missing_columns}")

    data = rerank_df.copy()
    data["_row_id"] = np.arange(len(data), dtype=np.int64)
    if density_index is None:
        density_index = build_local_waypoint_density_index(data)

    density_rows: List[Dict[str, object]] = []
    for _, row in data.iterrows():
        key = (
            str(row["site_id"]),
            str(row["floor"]),
            float(np.round(float(row["candidate_x"]), 1)),
            float(np.round(float(row["candidate_y"]), 1)),
        )
        features = density_index.get(key)
        if features is None:
            raise ValueError(
                "Could not map candidate coordinate to local density index: "
                f"site={key[0]}, floor={key[1]}, x={key[2]}, y={key[3]}"
            )
        density_row = {"_row_id": int(row["_row_id"])}
        density_row.update(features)
        density_rows.append(density_row)

    density_df = pd.DataFrame(density_rows)
    data = data.merge(density_df, on="_row_id", how="left")
    if data["local_waypoint_count_5m"].isna().any():
        raise ValueError("Local density feature build produced missing rows.")

    density_order = data.sort_values(
        [
            "group_id",
            "local_waypoint_count_5m",
            "local_waypoint_count_10m",
            "local_waypoint_nearest_dist_m",
            "rank",
            "_row_id",
        ],
        ascending=[True, False, False, True, True, True],
        na_position="last",
    ).copy()
    density_order["candidate_density_rank_within_group"] = density_order.groupby("group_id").cumcount() + 1
    data = data.merge(density_order[["_row_id", "candidate_density_rank_within_group"]], on="_row_id", how="left")
    if data["candidate_density_rank_within_group"].isna().any():
        raise ValueError("Local density feature build produced missing per-group density ranks.")

    data["candidate_density_rank_within_group"] = data["candidate_density_rank_within_group"].astype(np.int64)
    return data.sort_values("_row_id").drop(columns=["_row_id"]).reset_index(drop=True)


def safe_mean(array: np.ndarray) -> float:
    if len(array) == 0:
        return float("nan")
    return float(np.mean(array))


def classify_failure_mode(
    top5_recall: float,
    top10_recall: float,
    top50_recall: float,
    oracle_rank_mean: float,
    mean_bias_mag_m: float,
    catastrophic_outlier_ratio: float,
) -> str:
    if top5_recall < 0.2 or oracle_rank_mean > 10.0 or top50_recall < 0.8:
        return "candidate_recall_failure"
    if catastrophic_outlier_ratio >= 0.1:
        return "catastrophic_outlier_failure"
    if mean_bias_mag_m >= 4.0:
        return "systematic_bias_failure"
    return "mild_or_mixed_failure"


def classify_beam_signal(
    top5_recall: float,
    top10_recall: float,
    top50_recall: float,
    oracle_rank_mean: float,
    mean_bias_mag_m: float,
    catastrophic_outlier_ratio: float,
) -> str:
    if top5_recall < 0.2 or oracle_rank_mean > 10.0 or top50_recall < 0.8:
        return "fix_absolute_recall_first"
    if catastrophic_outlier_ratio >= 0.1:
        return "candidate_for_outlier_aware_beam"
    if mean_bias_mag_m >= 4.0:
        return "candidate_for_site_selective_beam"
    return "not_a_priority_for_beam"


def build_site_aggregate(path_df: pd.DataFrame, threshold_m: float) -> Dict[str, object]:
    n_points = int(path_df["n_points"].sum())
    weighted_sum = float(path_df["wifi_error_sum_m"].sum())
    top1 = float((path_df["top1_hits"] * path_df["n_points"]).sum() / max(n_points, 1))
    top5 = float((path_df["top5_hits"] * path_df["n_points"]).sum() / max(n_points, 1))
    top10 = float((path_df["top10_hits"] * path_df["n_points"]).sum() / max(n_points, 1))
    top50 = float((path_df["top50_hits"] * path_df["n_points"]).sum() / max(n_points, 1))
    catastrophic = float((path_df["catastrophic_count"].sum()) / max(n_points, 1))
    mean_bias_x = float((path_df["mean_bias_x"] * path_df["n_points"]).sum() / max(n_points, 1))
    mean_bias_y = float((path_df["mean_bias_y"] * path_df["n_points"]).sum() / max(n_points, 1))
    mean_bias_mag = float(np.linalg.norm([mean_bias_x, mean_bias_y]))

    return {
        "site_id": str(path_df["site_id"].iloc[0]),
        "n_paths": int(len(path_df)),
        "n_points": n_points,
        "wifi_mae_m": weighted_sum / max(n_points, 1),
        "pred_to_grid_mean_m": float((path_df["pred_to_grid_mean_m"] * path_df["n_points"]).sum() / max(n_points, 1)),
        "gt_to_train_oracle_mean_m": float((path_df["gt_to_train_oracle_mean_m"] * path_df["n_points"]).sum() / max(n_points, 1)),
        "oracle_rank_mean": float((path_df["oracle_rank_mean"] * path_df["n_points"]).sum() / max(n_points, 1)),
        "oracle_rank_median": float(path_df["oracle_rank_median"].median()),
        "top1_recall": top1,
        "top5_recall": top5,
        "top10_recall": top10,
        "top50_recall": top50,
        "catastrophic_outlier_ratio": catastrophic,
        "catastrophic_threshold_m": float(threshold_m),
        "mean_bias_x": mean_bias_x,
        "mean_bias_y": mean_bias_y,
        "mean_bias_mag_m": mean_bias_mag,
        "train_floor_count": int(path_df["train_floor_count"].max()),
        "train_path_count": int(path_df["train_path_count"].max()),
        "same_floor_train_paths": int(path_df["same_floor_train_paths"].max()),
        "same_floor_unique_waypoints": int(path_df["same_floor_unique_waypoints"].max()),
        "feature_source": str(path_df["feature_source"].iloc[0]),
        "model_kind": str(path_df["model_kind"].iloc[0]),
        "failure_mode": classify_failure_mode(top5, top10, top50, float((path_df["oracle_rank_mean"] * path_df["n_points"]).sum() / max(n_points, 1)), mean_bias_mag, catastrophic),
        "beam_candidate_signal": classify_beam_signal(top5, top10, top50, float((path_df["oracle_rank_mean"] * path_df["n_points"]).sum() / max(n_points, 1)), mean_bias_mag, catastrophic),
    }


def build_topk_summary(point_df: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for (site_id, floor), group in point_df.groupby(["site_id", "floor"], sort=False):
        selected_mae = float(group["selected_error_m"].mean())
        row: Dict[str, object] = {
            "site_id": str(site_id),
            "floor": str(floor),
            "n_points": int(len(group)),
            "selected_mae": selected_mae,
        }

        for k in SUMMARY_KS:
            oracle_col = f"oracle_distance_at_{k}"
            row[f"oracle_mae_at_{k}"] = float(group[oracle_col].mean())

        for threshold_m in SUMMARY_THRESHOLDS_M:
            threshold_label = f"{threshold_m}m"
            for k in SUMMARY_KS:
                hit_col = f"oracle_hit_at_{k}_{threshold_label}"
                row[f"recall_at_{k}_{threshold_label}"] = float(group[hit_col].mean())

        row["selected_minus_oracle_at_20"] = selected_mae - float(row["oracle_mae_at_20"])
        row["selected_minus_oracle_at_50"] = selected_mae - float(row["oracle_mae_at_50"])
        rows.append(row)

    if not rows:
        return pd.DataFrame()
    return (
        pd.DataFrame(rows)
        .sort_values(["selected_mae", "site_id", "floor"], ascending=[False, True, True])
        .reset_index(drop=True)
    )


def build_rerank_dataset(topk_candidates: pd.DataFrame) -> pd.DataFrame:
    required_columns = {
        "site_id",
        "path_id",
        "floor",
        "timestamp",
        "point_index",
        "rank",
        "candidate_index",
        "candidate_x",
        "candidate_y",
        "pred_x",
        "pred_y",
        "gt_x",
        "gt_y",
        "pred_to_candidate_m",
        "gt_to_candidate_m",
        "gt_nearest_rank",
        "is_gt_nearest",
    }
    missing_columns = sorted(required_columns - set(topk_candidates.columns))
    if missing_columns:
        raise ValueError(f"Top-K candidates are missing rerank dataset columns: {missing_columns}")

    group_columns = ["site_id", "path_id", "floor", "timestamp", "point_index"]
    data = topk_candidates.copy()
    data = data.sort_values(group_columns + ["rank"]).reset_index(drop=True)
    data["group_id"] = data[group_columns].astype(str).agg("|".join, axis=1)

    group_size = data.groupby("group_id")["rank"].transform("count").astype(np.float64)
    data["rank_norm"] = np.where(group_size > 1.0, (data["rank"].astype(np.float64) - 1.0) / (group_size - 1.0), 0.0)
    data["is_rank1"] = (data["rank"].astype(int) == 1).astype(int)

    data["dx_pred_to_candidate"] = data["candidate_x"].astype(np.float64) - data["pred_x"].astype(np.float64)
    data["dy_pred_to_candidate"] = data["candidate_y"].astype(np.float64) - data["pred_y"].astype(np.float64)
    data["abs_dx_pred_to_candidate"] = np.abs(data["dx_pred_to_candidate"])
    data["abs_dy_pred_to_candidate"] = np.abs(data["dy_pred_to_candidate"])

    data["label_distance_m"] = data["gt_to_candidate_m"].astype(np.float64)
    data["label_log1p_distance_m"] = np.log1p(data["label_distance_m"])
    data["label_hit3"] = (data["label_distance_m"] <= 3.0).astype(int)
    data["label_hit5"] = (data["label_distance_m"] <= 5.0).astype(int)
    data["label_is_gt_nearest"] = data["is_gt_nearest"].astype(int)

    data["group_oracle_distance_at_topk"] = data.groupby("group_id")["label_distance_m"].transform("min")
    data["label_is_group_best"] = np.isclose(
        data["label_distance_m"],
        data["group_oracle_distance_at_topk"],
        rtol=0.0,
        atol=1e-12,
    ).astype(int)
    data["group_gt_nearest_rank"] = data.groupby("group_id")["gt_nearest_rank"].transform("first").astype(int)
    data["group_raw_pred_error_m"] = np.linalg.norm(
        data[["pred_x", "pred_y"]].to_numpy(dtype=np.float64) - data[["gt_x", "gt_y"]].to_numpy(dtype=np.float64),
        axis=1,
    )

    rank1_errors = (
        data[data["rank"].astype(int) == 1][["group_id", "label_distance_m"]]
        .rename(columns={"label_distance_m": "group_rank1_candidate_error_m"})
        .drop_duplicates("group_id")
    )
    data = data.merge(rank1_errors, on="group_id", how="left")
    if data["group_rank1_candidate_error_m"].isna().any():
        raise ValueError("Rerank dataset has at least one group without a rank-1 candidate.")
    data["group_rank1_minus_oracle_m"] = data["group_rank1_candidate_error_m"] - data["group_oracle_distance_at_topk"]

    output_columns = [
        "site_id",
        "path_id",
        "floor",
        "timestamp",
        "point_index",
        "group_id",
        "rank",
        "candidate_index",
        "pred_x",
        "pred_y",
        "candidate_x",
        "candidate_y",
        "pred_to_candidate_m",
        "dx_pred_to_candidate",
        "dy_pred_to_candidate",
        "abs_dx_pred_to_candidate",
        "abs_dy_pred_to_candidate",
        "rank_norm",
        "is_rank1",
        "gt_x",
        "gt_y",
        "label_distance_m",
        "label_log1p_distance_m",
        "label_hit3",
        "label_hit5",
        "label_is_gt_nearest",
        "label_is_group_best",
        "group_oracle_distance_at_topk",
        "group_gt_nearest_rank",
        "group_raw_pred_error_m",
        "group_rank1_candidate_error_m",
        "group_rank1_minus_oracle_m",
    ]
    return data[output_columns].reset_index(drop=True)


def build_rerank_summary(rerank_df: pd.DataFrame) -> Dict[str, object]:
    if rerank_df.empty:
        raise ValueError("Cannot build rerank summary from an empty dataset.")

    groups = rerank_df.drop_duplicates("group_id").copy()
    rank1 = rerank_df[rerank_df["is_rank1"] == 1].drop_duplicates("group_id")
    if len(rank1) != len(groups):
        raise ValueError(f"Rerank summary expected one rank-1 row per group: rank1={len(rank1)}, groups={len(groups)}")

    oracle20 = (
        rerank_df[rerank_df["rank"].astype(int) <= 20]
        .groupby("group_id")["label_distance_m"]
        .min()
        .reindex(groups["group_id"])
        .to_numpy(dtype=np.float64)
    )
    oracle50 = (
        rerank_df[rerank_df["rank"].astype(int) <= 50]
        .groupby("group_id")["label_distance_m"]
        .min()
        .reindex(groups["group_id"])
        .to_numpy(dtype=np.float64)
    )
    if np.isnan(oracle20).any() or np.isnan(oracle50).any():
        raise ValueError("Rerank summary could not compute oracle distances for every group.")

    rank1_distance = rank1["label_distance_m"].to_numpy(dtype=np.float64)
    summary: Dict[str, object] = {
        "status": "ok",
        "n_groups": int(len(groups)),
        "n_rows": int(len(rerank_df)),
        "raw_pred_mae": float(groups["group_raw_pred_error_m"].mean()),
        "rank1_candidate_mae": float(rank1_distance.mean()),
        "oracle_mae_at_20": float(oracle20.mean()),
        "oracle_mae_at_50": float(oracle50.mean()),
        "rank1_hit3": float(np.mean(rank1_distance <= 3.0)),
        "rank1_hit5": float(np.mean(rank1_distance <= 5.0)),
        "oracle_hit3_at_50": float(np.mean(oracle50 <= 3.0)),
        "oracle_hit5_at_50": float(np.mean(oracle50 <= 5.0)),
        "notes": [
            "gt_x, gt_y, and label_* columns are training/diagnostic fields only.",
            "Inference features must not use gt_x, gt_y, or label_* columns.",
        ],
    }
    if "candidate_wifi_knn_score" in rerank_df.columns:
        wifi_scores = rerank_df["candidate_wifi_knn_score"].to_numpy(dtype=np.float64)
        summary["wifi_features"] = {
            "enabled": True,
            "missing_rssi": MISSING_WIFI_RSSI,
            "distance_missing_policy": "wifi_rssi_l1_distance_on_common and wifi_rssi_l2_distance_on_common are NaN when a candidate shares no BSSID with the validation point.",
            "candidate_wifi_source_count_gt0_ratio": float(np.mean(rerank_df["candidate_wifi_source_count"].to_numpy(dtype=np.float64) > 0.0)),
            "wifi_has_common_bssid_ratio": float(rerank_df["wifi_has_common_bssid"].mean()),
            "candidate_wifi_knn_score_min": float(np.min(wifi_scores)),
            "candidate_wifi_knn_score_mean": float(np.mean(wifi_scores)),
            "candidate_wifi_knn_score_median": float(np.median(wifi_scores)),
            "candidate_wifi_knn_score_p90": float(np.quantile(wifi_scores, 0.9)),
            "candidate_wifi_knn_score_max": float(np.max(wifi_scores)),
        }
    else:
        summary["wifi_features"] = {"enabled": False}
    if "candidate_wifi_best_source_score" in rerank_df.columns:
        def source_stats(column: str) -> Dict[str, float]:
            values = pd.to_numeric(rerank_df[column], errors="coerce").to_numpy(dtype=np.float64)
            finite_values = values[np.isfinite(values)]
            if len(finite_values) == 0:
                return {"min": float("nan"), "mean": float("nan"), "median": float("nan"), "p90": float("nan"), "max": float("nan")}
            return {
                "min": float(np.min(finite_values)),
                "mean": float(np.mean(finite_values)),
                "median": float(np.median(finite_values)),
                "p90": float(np.quantile(finite_values, 0.9)),
                "max": float(np.max(finite_values)),
            }

        source_counts = pd.to_numeric(rerank_df["candidate_wifi_source_count"], errors="coerce").to_numpy(dtype=np.float64)
        best_common = pd.to_numeric(rerank_df["candidate_wifi_best_common_bssid_count"], errors="coerce").to_numpy(dtype=np.float64)
        validation_visible = pd.to_numeric(rerank_df["source_wifi_validation_visible_bssid_count"], errors="coerce").to_numpy(dtype=np.float64)
        summary["source_wifi_features"] = {
            "enabled": True,
            "candidate_wifi_source_count_gt0_ratio": float(np.mean(source_counts > 0.0)),
            "source_wifi_no_common_bssid_ratio": float(np.mean(best_common <= 0.0)),
            "source_wifi_validation_no_wifi_ratio": float(np.mean(validation_visible <= 0.0)),
            "candidate_wifi_best_source_score": source_stats("candidate_wifi_best_source_score"),
            "candidate_wifi_top3_source_score_mean": source_stats("candidate_wifi_top3_source_score_mean"),
            "candidate_wifi_top5_source_score_mean": source_stats("candidate_wifi_top5_source_score_mean"),
            "candidate_wifi_best_source_l1": source_stats("candidate_wifi_best_source_l1"),
            "candidate_wifi_best_source_cosine": source_stats("candidate_wifi_best_source_cosine"),
        }
    else:
        summary["source_wifi_features"] = {"enabled": False}
    temporal_columns = [
        "raw_pred_step_from_prev_m",
        "raw_pred_step_to_next_m",
        "candidate_step_from_prev_rank1_m",
        "candidate_step_to_next_rank1_m",
        "candidate_distance_to_prev_raw_pred_m",
        "candidate_distance_to_next_raw_pred_m",
        "candidate_temporal_smoothness_rank1_m",
        "timestamp_norm_in_path",
        "point_index_norm_in_path",
    ]
    density_columns = [
        "local_waypoint_count_3m",
        "local_waypoint_count_5m",
        "local_waypoint_count_10m",
        "local_waypoint_nearest_dist_m",
        "local_waypoint_mean_dist_5nn_m",
        "local_waypoint_mean_dist_10nn_m",
        "candidate_is_sparse_area",
        "candidate_density_rank_within_group",
    ]
    if all(column in rerank_df.columns for column in temporal_columns + density_columns):
        def finite_stats(column: str) -> Dict[str, float]:
            values = pd.to_numeric(rerank_df[column], errors="coerce").to_numpy(dtype=np.float64)
            finite_values = values[np.isfinite(values)]
            if len(finite_values) == 0:
                return {"min": float("nan"), "mean": float("nan"), "median": float("nan"), "p90": float("nan"), "max": float("nan")}
            return {
                "min": float(np.min(finite_values)),
                "mean": float(np.mean(finite_values)),
                "median": float(np.median(finite_values)),
                "p90": float(np.quantile(finite_values, 0.9)),
                "max": float(np.max(finite_values)),
            }

        summary["temporal_density_features"] = {
            "enabled": True,
            "temporal_unavailable_policy": "Previous-step features are NaN at path starts; next-step features are NaN at path ends.",
            "raw_pred_step_from_prev_nan_ratio": float(rerank_df["raw_pred_step_from_prev_m"].isna().mean()),
            "raw_pred_step_to_next_nan_ratio": float(rerank_df["raw_pred_step_to_next_m"].isna().mean()),
            "candidate_step_from_prev_rank1_nan_ratio": float(rerank_df["candidate_step_from_prev_rank1_m"].isna().mean()),
            "candidate_step_to_next_rank1_nan_ratio": float(rerank_df["candidate_step_to_next_rank1_m"].isna().mean()),
            "candidate_distance_to_prev_raw_pred_nan_ratio": float(rerank_df["candidate_distance_to_prev_raw_pred_m"].isna().mean()),
            "candidate_distance_to_next_raw_pred_nan_ratio": float(rerank_df["candidate_distance_to_next_raw_pred_m"].isna().mean()),
            "candidate_temporal_smoothness_rank1_nan_ratio": float(rerank_df["candidate_temporal_smoothness_rank1_m"].isna().mean()),
            "local_waypoint_count_3m": finite_stats("local_waypoint_count_3m"),
            "local_waypoint_count_5m": finite_stats("local_waypoint_count_5m"),
            "local_waypoint_count_10m": finite_stats("local_waypoint_count_10m"),
            "local_waypoint_nearest_dist_m": finite_stats("local_waypoint_nearest_dist_m"),
            "local_waypoint_mean_dist_5nn_m": finite_stats("local_waypoint_mean_dist_5nn_m"),
            "local_waypoint_mean_dist_10nn_m": finite_stats("local_waypoint_mean_dist_10nn_m"),
            "candidate_is_sparse_area_ratio": float(rerank_df["candidate_is_sparse_area"].mean()),
        }
    else:
        summary["temporal_density_features"] = {"enabled": False}
    return summary


def main() -> None:
    args = parse_args()
    if args.topk < max(SUMMARY_KS):
        raise ValueError(f"--topk must be at least {max(SUMMARY_KS)} to compute required summary columns.")

    cfg = load_yaml(resolve_path(args.config))
    base_summary = load_json(resolve_path(args.site_summary_source))
    site_ids = get_site_ids(args, base_summary)

    holdout_fraction = float(get_effective_setting(args.holdout_fraction, base_summary, "holdout_fraction", 0.1))
    max_holdout_paths = int(get_effective_setting(args.max_holdout_paths, base_summary, "max_holdout_paths", 1))
    seed = int(get_effective_setting(args.seed, base_summary, "seed", 42))

    train_dir = PROJECT_ROOT / cfg["paths"]["train_dir"]
    prediction_artifact = load_prediction_artifact(resolve_path(args.prediction_artifact))
    path_rows: List[Dict[str, object]] = []
    topk_candidate_rows: List[Dict[str, object]] = []
    topk_point_rows: List[Dict[str, object]] = []

    for site_index, site_id in enumerate(site_ids, start=1):
        path_files = list_site_paths(train_dir / site_id)
        train_files, holdout_files = split_holdout_paths(
            path_files=path_files,
            holdout_fraction=holdout_fraction,
            seed=seed + site_index,
            max_holdout_paths=max_holdout_paths,
        )
        if not holdout_files:
            continue

        train_meta = reconstruct_site_meta(train_files, site_id)
        train_floor_count = int(train_meta["floor"].astype(str).nunique())

        for holdout_file in holdout_files:
            path_df = get_path_predictions(prediction_artifact, site_id, holdout_file.stem)
            floor = str(path_df["floor"].iloc[0])
            train_waypoints = collect_same_floor_training_waypoints(train_files, floor)
            if len(train_waypoints) == 0:
                continue

            gt_xy = path_df[["x", "y"]].to_numpy(dtype=np.float64)
            pred_xy = path_df[["pred_x", "pred_y"]].to_numpy(dtype=np.float64)
            timestamps = path_df["timestamp"].to_numpy(dtype=np.int64)
            point_indices = path_df["point_index"].to_numpy(dtype=np.int64)

            gt_to_train = np.linalg.norm(gt_xy[:, np.newaxis, :] - train_waypoints[np.newaxis, :, :], axis=2)
            pred_to_train = np.linalg.norm(pred_xy[:, np.newaxis, :] - train_waypoints[np.newaxis, :, :], axis=2)
            gt_nearest_idx = np.argmin(gt_to_train, axis=1)

            ranks: List[int] = []
            for point_index, candidate_index in enumerate(gt_nearest_idx):
                order = np.argsort(pred_to_train[point_index])
                rank = int(np.where(order == candidate_index)[0][0]) + 1
                ranks.append(rank)

                candidate_order = order[: min(args.topk, len(order))]
                candidate_gt_distances = gt_to_train[point_index, candidate_order]
                point_row: Dict[str, object] = {
                    "site_id": site_id,
                    "path_id": holdout_file.stem,
                    "floor": floor,
                    "timestamp": int(timestamps[point_index]),
                    "point_index": int(point_indices[point_index]),
                    "selected_error_m": float(np.linalg.norm(pred_xy[point_index] - gt_xy[point_index])),
                    "gt_nearest_index": int(candidate_index),
                    "gt_nearest_rank": rank,
                }

                for k in SUMMARY_KS:
                    k_eff = min(k, len(candidate_order))
                    oracle_distance = float(np.min(candidate_gt_distances[:k_eff]))
                    point_row[f"oracle_distance_at_{k}"] = oracle_distance
                    for threshold_m in SUMMARY_THRESHOLDS_M:
                        threshold_label = f"{threshold_m}m"
                        point_row[f"oracle_hit_at_{k}_{threshold_label}"] = int(oracle_distance <= float(threshold_m))

                topk_point_rows.append(point_row)

                for candidate_rank, topk_candidate_index in enumerate(candidate_order, start=1):
                    candidate_xy = train_waypoints[topk_candidate_index]
                    topk_candidate_rows.append(
                        {
                            "site_id": site_id,
                            "path_id": holdout_file.stem,
                            "floor": floor,
                            "timestamp": int(timestamps[point_index]),
                            "point_index": int(point_indices[point_index]),
                            "rank": int(candidate_rank),
                            "candidate_index": int(topk_candidate_index),
                            "candidate_x": float(candidate_xy[0]),
                            "candidate_y": float(candidate_xy[1]),
                            "pred_x": float(pred_xy[point_index, 0]),
                            "pred_y": float(pred_xy[point_index, 1]),
                            "gt_x": float(gt_xy[point_index, 0]),
                            "gt_y": float(gt_xy[point_index, 1]),
                            "pred_to_candidate_m": float(pred_to_train[point_index, topk_candidate_index]),
                            "gt_to_candidate_m": float(gt_to_train[point_index, topk_candidate_index]),
                            "gt_nearest_index": int(candidate_index),
                            "gt_nearest_rank": rank,
                            "is_gt_nearest": int(topk_candidate_index == candidate_index),
                        }
                    )

            ranks_arr = np.asarray(ranks, dtype=np.int64)
            errors = pred_xy - gt_xy
            err_mag = np.linalg.norm(errors, axis=1)
            mean_bias = errors.mean(axis=0)

            path_rows.append(
                {
                    "site_id": site_id,
                    "path_id": holdout_file.stem,
                    "floor": floor,
                    "n_points": int(len(path_df)),
                    "wifi_mae_m": float(err_mag.mean()),
                    "wifi_error_sum_m": float(err_mag.sum()),
                    "pred_to_grid_mean_m": float(np.min(pred_to_train, axis=1).mean()),
                    "gt_to_train_oracle_mean_m": float(np.min(gt_to_train, axis=1).mean()),
                    "oracle_rank_mean": float(ranks_arr.mean()),
                    "oracle_rank_median": float(np.median(ranks_arr)),
                    "top1_hits": float(np.mean(ranks_arr <= 1)),
                    "top5_hits": float(np.mean(ranks_arr <= 5)),
                    "top10_hits": float(np.mean(ranks_arr <= 10)),
                    "top50_hits": float(np.mean(ranks_arr <= 50)),
                    "catastrophic_count": int(np.sum(err_mag >= args.catastrophic_threshold_m)),
                    "catastrophic_ratio": float(np.mean(err_mag >= args.catastrophic_threshold_m)),
                    "mean_bias_x": float(mean_bias[0]),
                    "mean_bias_y": float(mean_bias[1]),
                    "mean_bias_mag_m": float(np.linalg.norm(mean_bias)),
                    "error_std_m": float(err_mag.std()),
                    "train_floor_count": train_floor_count,
                    "train_path_count": int(len(train_files)),
                    "same_floor_train_paths": int(sum(path.parent.name == floor for path in train_files)),
                    "same_floor_unique_waypoints": int(len(train_waypoints)),
                    "feature_source": str(path_df["feature_source"].iloc[0]),
                    "model_kind": str(path_df["model_kind"].iloc[0]),
                    "failure_mode": classify_failure_mode(
                        float(np.mean(ranks_arr <= 5)),
                        float(np.mean(ranks_arr <= 10)),
                        float(np.mean(ranks_arr <= 50)),
                        float(ranks_arr.mean()),
                        float(np.linalg.norm(mean_bias)),
                        float(np.mean(err_mag >= args.catastrophic_threshold_m)),
                    ),
                    "beam_candidate_signal": classify_beam_signal(
                        float(np.mean(ranks_arr <= 5)),
                        float(np.mean(ranks_arr <= 10)),
                        float(np.mean(ranks_arr <= 50)),
                        float(ranks_arr.mean()),
                        float(np.linalg.norm(mean_bias)),
                        float(np.mean(err_mag >= args.catastrophic_threshold_m)),
                    ),
                }
            )

    path_metrics = pd.DataFrame(path_rows)
    if path_metrics.empty:
        raise ValueError("No candidate recall diagnostics were produced.")

    path_metrics = path_metrics.sort_values(["wifi_mae_m", "oracle_rank_mean"], ascending=[False, False]).reset_index(drop=True)
    site_metrics = pd.DataFrame(
        [build_site_aggregate(site_df.reset_index(drop=True), args.catastrophic_threshold_m) for _, site_df in path_metrics.groupby("site_id", sort=False)]
    )
    site_metrics = site_metrics.sort_values(["wifi_mae_m", "oracle_rank_mean"], ascending=[False, False]).reset_index(drop=True)
    topk_candidates = pd.DataFrame(topk_candidate_rows)
    topk_points = pd.DataFrame(topk_point_rows)
    if topk_candidates.empty or topk_points.empty:
        raise ValueError("No Top-K candidate diagnostics were produced.")
    topk_summary = build_topk_summary(topk_points)
    rerank_dataset = build_rerank_dataset(topk_candidates)
    if args.include_rerank_wifi_features and args.include_rerank_source_wifi_features:
        rerank_dataset = attach_source_wifi_features_to_rerank_dataset(
            rerank_df=rerank_dataset,
            site_ids=site_ids,
            train_dir=train_dir,
            n_bssid=int(cfg["features"]["n_bssid"]),
            window_ms=int(cfg["features"]["window_ms"]),
            holdout_fraction=holdout_fraction,
            seed=seed,
            max_holdout_paths=max_holdout_paths,
            source_wifi_topn=int(args.source_wifi_topn),
            rssi_clip_min=float(args.wifi_rssi_clip_min),
            rssi_clip_max=float(args.wifi_rssi_clip_max),
            include_aggregate_wifi_features=True,
            wifi_knn_topn=int(args.wifi_knn_topn),
        )
    elif args.include_rerank_wifi_features:
        rerank_dataset = attach_wifi_features_to_rerank_dataset(
            rerank_df=rerank_dataset,
            site_ids=site_ids,
            train_dir=train_dir,
            n_bssid=int(cfg["features"]["n_bssid"]),
            window_ms=int(cfg["features"]["window_ms"]),
            holdout_fraction=holdout_fraction,
            seed=seed,
            max_holdout_paths=max_holdout_paths,
            wifi_knn_topn=int(args.wifi_knn_topn),
            rssi_clip_min=float(args.wifi_rssi_clip_min),
            rssi_clip_max=float(args.wifi_rssi_clip_max),
        )
    elif args.include_rerank_source_wifi_features:
        rerank_dataset = attach_source_wifi_features_to_rerank_dataset(
            rerank_df=rerank_dataset,
            site_ids=site_ids,
            train_dir=train_dir,
            n_bssid=int(cfg["features"]["n_bssid"]),
            window_ms=int(cfg["features"]["window_ms"]),
            holdout_fraction=holdout_fraction,
            seed=seed,
            max_holdout_paths=max_holdout_paths,
            source_wifi_topn=int(args.source_wifi_topn),
            rssi_clip_min=float(args.wifi_rssi_clip_min),
            rssi_clip_max=float(args.wifi_rssi_clip_max),
            include_aggregate_wifi_features=False,
            wifi_knn_topn=int(args.wifi_knn_topn),
        )
    if args.include_rerank_temporal_density_features:
        rerank_dataset = attach_temporal_features_to_rerank_dataset(rerank_dataset)
        density_index = build_local_waypoint_density_index(
            rerank_df=rerank_dataset,
            density_radius_small=float(args.density_radius_small),
            density_radius_medium=float(args.density_radius_medium),
            density_radius_large=float(args.density_radius_large),
        )
        rerank_dataset = attach_local_density_features_to_rerank_dataset(
            rerank_df=rerank_dataset,
            density_index=density_index,
        )
    rerank_summary = build_rerank_summary(rerank_dataset)

    summary = {
        "status": "ok",
        "target_route": "absolute_baseline",
        "site_ids": site_ids,
        "seed": seed,
        "holdout_fraction": holdout_fraction,
        "max_holdout_paths": max_holdout_paths,
        "catastrophic_threshold_m": float(args.catastrophic_threshold_m),
        "n_paths": int(len(path_metrics)),
        "n_sites": int(len(site_metrics)),
        "n_points": int(path_metrics["n_points"].sum()),
        "site_priority_order": site_metrics[
            ["site_id", "wifi_mae_m", "failure_mode", "beam_candidate_signal", "top10_recall", "catastrophic_outlier_ratio", "mean_bias_mag_m"]
        ].to_dict(orient="records"),
        "best_beam_candidates": site_metrics[site_metrics["beam_candidate_signal"].isin([
            "candidate_for_site_selective_beam",
            "candidate_for_outlier_aware_beam",
        ])][
            ["site_id", "wifi_mae_m", "beam_candidate_signal", "top10_recall", "catastrophic_outlier_ratio", "mean_bias_mag_m"]
        ].to_dict(orient="records"),
        "fix_recall_first_sites": site_metrics[site_metrics["beam_candidate_signal"] == "fix_absolute_recall_first"][
            ["site_id", "wifi_mae_m", "top10_recall", "top50_recall", "oracle_rank_mean"]
        ].to_dict(orient="records"),
        "environment": get_environment_snapshot(),
    }

    path_out = resolve_path(args.path_out)
    site_out = resolve_path(args.site_out)
    summary_out = resolve_path(args.summary_out)
    topk_candidate_out = resolve_path(args.topk_candidate_out)
    topk_summary_out = resolve_path(args.topk_summary_out)
    rerank_dataset_out = resolve_path(args.rerank_dataset_out)
    rerank_summary_out = resolve_path(args.rerank_summary_out)
    path_out.parent.mkdir(parents=True, exist_ok=True)
    topk_candidate_out.parent.mkdir(parents=True, exist_ok=True)
    topk_summary_out.parent.mkdir(parents=True, exist_ok=True)
    rerank_dataset_out.parent.mkdir(parents=True, exist_ok=True)
    rerank_summary_out.parent.mkdir(parents=True, exist_ok=True)

    path_metrics.to_csv(path_out, index=False)
    site_metrics.to_csv(site_out, index=False)
    topk_candidates.to_csv(topk_candidate_out, index=False)
    topk_summary.to_csv(topk_summary_out, index=False)
    rerank_dataset.to_csv(rerank_dataset_out, index=False)
    with open(summary_out, "w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2, ensure_ascii=False)
    with open(rerank_summary_out, "w", encoding="utf-8") as handle:
        json.dump(rerank_summary, handle, indent=2, ensure_ascii=False)

    print(f"Saved path metrics: {path_out}")
    print(f"Saved site metrics: {site_out}")
    print(f"Saved summary     : {summary_out}")
    print(f"Saved Top-K points: {topk_candidate_out}")
    print(f"Saved Top-K summary: {topk_summary_out}")
    print(f"Saved rerank dataset: {rerank_dataset_out}")
    print(f"Saved rerank summary: {rerank_summary_out}")


if __name__ == "__main__":
    main()
